### ISSUE TITLE
file parameter in service uneditable if parameter contains spaces

### ISSUE THREAD

**Issue by heller-droxit** [droxit/roxcomposer-gui#18]
After editing the "path" parameter of a service so that the parameter contains a space and saving the change, the path parameter becomes uneditable.

Example: see screenshot
![screenshot](https://user-images.githubusercontent.com/49147964/55569459-e92af080-5701-11e9-9edb-1321905ee3c2.png)

**Comment by hecktor-droxit** [comment]
Fixed.
